
# travis config

sudo: required
warnings_are_errors: false

language: r
cache: packages

before_install:
  - R -e "install.packages(c('devtools','testthat'))"
  - R -e "devtools::install_deps('./pkg')"
  - cd ./cbsots

r_packages:
  - rmarkdown

notifications:
  email:
    on_success: change
    on_failure: always 

