
# travis config

sudo: required
warnings_are_errors: false

language: r
cache: packages

before_install:
  - R -e "install.packages(c('devtools','testthat', 'drat'))"
  - R -e "drat::addRepo('timemod');install.packages('regts')"
  - R -e "devtools::install_deps('./cbsots')"
  - cd ./cbsots

r_packages:
  - rmarkdown

notifications:
  email:
    on_success: change
    on_failure: always 

